---
- name: Install Jenkins Agent with Docker and kubectl
  hosts: jenkins_agents
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install build tools
      apt:
        name:
        - openjdk-21-jdk
        - maven
        - docker.io
        state: present
        update_cache: yes
    
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        dest: /tmp/kubernetes-release.key
        mode: "0644"

    - name: Convert Kubernetes GPG key
      command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /

    - name: Update apt cache after adding Kubernetes repo
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present